##############################
# constants for Basic Information Tab Widgets
#
XSTART = 20
CLASSGAP = 220
CLASSDATASIZE = 170
CLASSNAMESIZE = 90
COMBOBOXSIZE = 35
WIDGET_H = 20
PROFNAMEWIDTH = 60
NUMBERQUESTION_Y = 50
DATA_CATEGORY_LINE = 100
PROF_DATA_GAP = 70
PROF_NAME_INDENT = 50
PROF_NCLASS_INDENT = 120
CLASS_NAME_INDENT = 160