##############################
# constants for Basic Information Tab Widgets
#
XSTART = 20
CLASSGAP = 220
CLASSDATASIZE = 210
CLASSNAMESIZE = 100
COMBOBOXSIZE = 50
WIDGET_H = 20
PROFNAMEWIDTH = 50
NUMBERQUESTION_Y = 50
DATA_CATEGORY_LINE = 100
PROF_DATA_GAP = 50
PROF_NAME_INDENT = 80
PROF_NCLASS_INDENT = 130
CLASS_NAME_INDENT = 160